### ISSUE TITLE
fix multi processors accessing same file

### ISSUE THREAD

**Issue by arulalant** [raghu330/iGui#14]
I found that multiple processors are accessing same file while creating grib2 file, after regridding.

It creates problem while reading it again!

use lock!

**Comment by arulalant** [comment]
Solved this issue in the pull request #16

**Comment by raghu330** [comment]
Arul,

Think I messed up the git-head, I just did git rebase origin in order to
push the comments.. Things seem like I am back in 1960s everything in B&W
and with Shivaji Ganeshan dancing around with Jayalalitha lol:)

Chalo meet you later afternoon..
Cheers
Raghu

On Fri, Dec 11, 2015 at 7:46 PM, Arulalan.T notifications@github.com
wrote:

> Solved this issue in the pull request #16
> https://github.com/raghu330/iGui/pull/16
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raghu330/iGui/issues/14#issuecomment-163945690.

## 

Raghavendra S. Mupparthy
614-302-6377 (M)
http://hcgl.eng.ohio-state.edu/~mupparthy.1
